[workspace]
resolver = "2"

members = ["crypto_agility_crypto_api", "crypto_agility_crypto_api/examples/*"]
exclude = ["./liboqs-rust", "./rust-hpke", "./argyle-kyber"]

[patch.crates-io]
hpke.path = "hpke-rust/"
oqs-sys.path = "liboqs-rust/oqs-sys"
safe_pqc_kyber.path = "argyle-kyber/"
